import type { Metadata } from 'next'
import { Mulish } from 'next/font/google'

import styles from './layout.module.scss'

const mulish = Mulish({
  variable: '--font-mulish',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${styles.body} ${mulish.variable}`}>{children}</body>
    </html>
  )
}
